### ISSUE TITLE
503 Error after successful stack creation

### ISSUE THREAD

**Issue by lpmagnuson** [hybox/aws#158]
Hello, I've followed the instructions to install hybox on AWS but after successful creation of all stacks, I receive a 503 error on AWS.  I have a couple of questions that make me think I'm doing something wrong in the setup:

1)  How do I populate the SecretKeyBase in the params json?  I wasn't sure how to generate this prior to the stack being created, so I left it blank in the params json.  The creation of the stack was successful despite this.

2) I made up a random password to populate the FcrepoDatabasePassword and the DatabasePassword - was I supposed to make something up for these values, or leave blank, or use some other value?

3)I've tried two different S3KeyPrefixes - "branch/master" and "current" with the WebappS3Key value being "hyku/current/hyku.zip".  Which S3KeyPrefix should I use?  I've attached a copy of my .json params file, with passwords and keys stripped out.

If you have any other troubleshooting advice for what might be going wrong to result in a 503 error with the stacks, please do let me know!  I'm a AWS n00b so any pointers are appreciated. Our test repo on AWS is hyku.palnischolar.org.  Thanks in advance for any advice!

[palni_copy.txt](https://github.com/hybox/aws/files/1088866/palni_copy.txt)

**Comment by lpmagnuson** [comment]
Update-  I'm pretty sure I've narrowed this down to the SecretKeyBase issue.  I've found in the ElasticBeanstalk Health dashboard the SecretKeyBase from the error output for the Rails app.  I'm a bit unsure now how to update the app - I've gone into the main 'hyku' stack and set to update the stack, replacing the SecretKeyBase with the key base found in the EB Health dashboard output, but I keep getting errors attempting to update, with the update rolling back.

Again, sorry, I'm sure these issues are AWS newbie issues, but I really appreciate any guidance!

**Comment by mjgiarlo** [comment]
Advice for @lpmagnuson, @eefahy @bbranan @cbeer @jcoyne ?

**Comment by lpmagnuson** [comment]
I figured it out.  I added the SecretKeyBase I found in the Elastic Beanstalk Health error report for the Hyku Webapp to my params .json file and ran this using the AWS CLI:

aws cloudformation update-stack --stack-name hyku --template-body https://s3.amazonaws.com/hybox-deployment-artifacts/cloudformation/current/templates/stack.yaml --capabilities CAPABILITY_IAM --region us-east-1 --parameters file:///some/directory/structure/aws-master/params/palni.json

There's probably a better way to do it - if so, let me know - but this eliminated the 503 error problems and my Rails app successfully loaded through the browser.  Yay! :)

**Comment by bbranan** [comment]
Well done @lpmagnuson,

You were clearly right that the issue was a missing SecretKeyBase value. This value is required by the Hyku webapp because it is a Rails-based application. There are notes here that talk about how that value is generated: https://til.hashrocket.com/posts/8b8b4d00a3-generate-a-rails-secret-key. 

The password you set for the FcrepoDatabasePassword and DatabasePassword fields are just that, passwords for those databases, so made the right choice to populate them. What value you use doesn't really matter (though strong passwords are recommended, of course.)

At this point the S3KeyPrefix can be either "current" or "branch/master", so long as what you use matches the path you use for the template body in the command line call.
